//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BetSystem.java
//  @ Date : 06.05.2019
//  @ Author : 
//
//




public class BetSystem {
	public Race races;
	public void betOnRaceOnHorse(User user, int raceId, String horseName, double amount) {
	
	}
	
	public double doIWin(User user, int raceId) {
	
	}
}
