//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Horse.java
//  @ Date : 06.05.2019
//  @ Author : 
//
//




public class Horse {
	private Object place;
	public Object name;
	public void setPlace(int place) {
	
	}
	
	public int getPlace() {
	
	}
}
