//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Race.java
//  @ Date : 06.05.2019
//  @ Author : 
//
//




public class Race {
	public Horse horses;
	public BetSystem races;
	public void beforeStart() {
	
	}
	
	public Horse[] race() {
	
	}
}
